version: '3.8'
services:
  oracle-xe:
    image: gvenzl/oracle-xe:21.3.0
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: changemeinprod!
      APP_USER: userfortest
      APP_USER_PASSWORD: changemeinprod!
